### ISSUE TITLE
Castbar doesn't work when using Bongos

### ISSUE THREAD

**Issue by Nescitum** [SabineWren/Quiver#8]
As the title states, 

using this addon while using bongos makes the cast bar not appear.

**Comment by SabineWren** [comment]
Try putting the spellbook ability on your action bars, but separately use a macro to cast it `/cast Aimed Shot`

**Comment by Nescitum** [comment]
I have tried using it with no macro, and with a macro. if its in the bongos action bar straight from the spell book it still doesn't appear. manually clicking it from the spell book does make it appear. I was assuming it's something with the way bongos changes the action bars.

**Comment by tthe3d** [comment]
Castbar worked for me with the /qqaimedshot and the others , but today just stopped. Haven't touch the settings of Quiver , but I installed some other swing timers for my warrior and it disappeared. I wonder what's the problem , since i deleted the other swing timmers , reinstalled quiver , deleted WDB folder, it just doesnt work with /qqaimedshot , etcc. anymore

**Comment by SabineWren** [comment]
I installed Bongos and couldn't replicate this:
- Bongos castbar never shows unless I programmatically select the frame and `:Show()` it. This is true even without Quiver or pfUI enabled.
- Quiver's castbar and auto shot bar show normally, regardless of which Bongos addons are enabled.

**Comment by SabineWren** [comment]
I rewrote the cast detection code on a [development branch](https://github.com/SabineWren/Quiver/tree/bundle). The new code works provided any action bar icon has the correct spell texture, even if it's a macro. That most likely fixes all edge cases with the cast bar not working, so I'm closing this issue.

If you want to try it, that branch has a build step:
`npm install && npm run bundle`
